### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by peterneubauer** [joewhite86/node-neo4j-embedded#1]
@joewhite86 cool stuff! Mind writing a blog or screencast to introduce this to the broader masses?

**Comment by joewhite86** [comment]
Thanks @peterneubauer. 
Sure, let you know when I've something written.

**Comment by joewhite86** [comment]
So, finally, here you are:
http://joewhite86.wordpress.com/2013/07/08/introducing-neo4j-embedded-a-neo4j-driver-for-node-js/
